### ISSUE TITLE
Contact City of Fort Collins for consumable data

### ISSUE THREAD

**Issue by redisforlosers** [CodeForFoco/solar-scorecard#1]
City of Fort Collins has expressed a desire in the past to make more data publicly available, let's take them up on that offer to acquire the data we need for this project.

Our contact is Olivia Terrell (oterrell@fcgov.com), the Fort Collins Data Specialist.

We're specifically looking for the following information:
Photovoltaic power rating (KW and number of modules) for any permits issued in the City that are currently publicly available.

Ideally this data would be made available at [https://opencity.fcgov.com/](https://opencity.fcgov.com/)

**Comment by abettermap** [comment]
- [Search page](http://amos.fcgov.com/CitizenAccess/) (click **Search Additional Criteria** and make sure `Yes` is checked under `Photovoltaic System`
- [Permit example](http://amos.fcgov.com/CitizenAccess/Cap/CapDetail.aspx?Module=Building&TabName=Building&capID1=17RAL&capID2=00000&capID3=00323&agencyCode=FTCOLLINS&IsToShowInspection=) (need the **Work Description** section, specifically `kW` and `number of modules`

**Comment by abettermap** [comment]
This is the gold:
![screen shot 2017-05-11 at 8 08 35 pm](https://cloud.githubusercontent.com/assets/4974087/25979475/e450aeea-3685-11e7-9d0b-6f5be73524fb.jpg)

**Comment by redisforlosers** [comment]
email was sent to Olivia today, awaiting response

**Comment by abettermap** [comment]
### Updates

- Olivia has been very responsive and receptive, and is willing to help us out
- We requested Socrata (OpenCity) integration, which is still a possibility, but the person in charge of the data we want is currently occupied with another project
- Olivia will keep us in the loop but cannot confirm a timeframe, so we may move forward with our original data scraping plan until we hear otherwise

Either way, we should be able to start on the rough goals for design and functionality.

**Comment by idcrook** [comment]
Copying an email from Olivia, sent today

> **Olivia Terrell** 7:55 AM (10 hours ago)
> to me, Ian, englehorn, jason 
> 
> Ian, David and team,
>  
> We have located the database that pulls for the http://amos.fcgov.com/CitizenAccess/ site, but it is going to take some coding to get everything into Socrata. The vendor already has an API and we are exploring what it will take to get that in the meanwhile.
>  
> I do not know the timeline for this yet—my contact for that database just got back with me this morning.
>  
> Olivia

**Comment by abettermap** [comment]
Update 6/23: Olivia responded to Ian's email suggesting a meeting to go over data specifics. Just waiting to establish a time and date.

**Comment by abettermap** [comment]
Update Nov. 7: City of Fort Collins has uploaded it's data on OpenData! https://opencity.fcgov.com/Environmental-Health/Solar-Systems-Data/hdei-4qfu/data
