### ISSUE TITLE
Add index.html to github pages

### ISSUE THREAD

**Issue by JordanMajd** [CodeForFoco/solar-scorecard#26]
Currently the site is accessible at [http://codeforfoco.org/solar-scorecard/stairstep.html](http://codeforfoco.org/solar-scorecard/stairstep.html). The `gh-pages` branch should have an `index.html` branch so that the project can be viewed at [http://codeforfoco.org/solar-scorecard](http://codeforfoco.org/solar-scorecard).

This page should also be linked in the repo [README.md](/README.md) and on the project page on the code for foco website.

**Comment by ijskor** [comment]
Keywords to include in website for marketing:
'Solar Scorecard Version-Boulder'

Boulder Climate Action Plan
Xcel energy (Boulder)
Boulder Colorado Climate Change
Clean Energy Action
Boulder Energy
Future City
Green Energy Pledge
#Readyfor100 
100 Percent renewable energy commitment

**Comment by abettermap** [comment]
@ijskor I made your comment a separate issue: #27

**Comment by abettermap** [comment]
Made the cffc link its own issue: https://github.com/CodeForFoco/codeforfoco.github.io/issues/135
