### ISSUE TITLE
Charts

### ISSUE THREAD

**Issue by ijskor** [CodeForFoco/solar-scorecard#3]
Things to think about when creating the chart.
1) for sandbox solar 's site it will be at the top and be a hook for users - so maybe it needs to be a horizontal bar, meter, or something?
2) it will ultimately correlate to the users contriubtion to renewable energy when they buy a solar panel. (Small visible changes?)
3) hopefully we can replicate it for other towns, cities, utilities.
4)open to suggestions

**Comment by redisforlosers** [comment]
We decided to start with a bar chart of some kind, however any interesting and readable graphic will work.  There was some discussion about responsive design being integrated into the graph, or if that's not possible providing multiple graphs for different sizes.

**Comment by dgendill** [comment]
I think the graphs we currently have are a good start.  I'm going to close this and we can open a new ticket if we need something else.
