### ISSUE TITLE
Decide on style approach

### ISSUE THREAD

**Issue by ijskor** [CodeForFoco/solar-scorecard#34]
Would like to copy similar styling for the solar-scorecard portion of the website. (i.e Background, Scroll Effects, Navigation Bar, etc.)

And have it linked to the repo so that it automatically updates when main page is updated.

**Comment by abettermap** [comment]
@ijskor 

I think I saw you mention something in Slack about some design ideas. If so, does this issue still apply? It's certainly doable, but it could get messy dealing with two separate repos.

Any thoughts on taking the lazier (but potentially prettier) approach of using an existing style like Google's [Material Design](https://material.io/guidelines/)?

**Comment by ijskor** [comment]
I like the idea of a quick design approach. 

My friend designed a general layout idea that we can work from.

![24116373_10155161152651274_317844075_o](https://user-images.githubusercontent.com/28639805/33465484-4cb7edda-d605-11e7-9fc6-5369bbbb1853.png)

**Comment by abettermap** [comment]
Going to roll with Material Design. Nice and cohesive and well-thought-out. Will have a better result than if we Frankenstein it.

**Comment by abettermap** [comment]
This issue changed names and purposes like four times, but I think we can consider it complete since we decided on a Vue + Material combo.

I'll make the mockup step a separate issue since we've settled on a single-page, non-scrollable layout (except the nav).
