### ISSUE TITLE
Use real data

### ISSUE THREAD

**Issue by abettermap** [CodeForFoco/solar-scorecard#36]
Actual PV data is available on Socrata, use that instead of dummy data: https://opencity.fcgov.com/Environmental-Health/Solar-Systems-Data/hdei-4qfu/data

Archive/delete dummy data when done.

**Comment by ijskor** [comment]
Updated Link to Socrata Solar App

https://opencity.fcgov.com/Economic-Health/Solar-Systems-Data/3ku5-x4k9

**Comment by ijskor** [comment]
App Token
Grl9BP2WdpCsAdxGtNqLSkuNr

**Comment by abettermap** [comment]
This seems like it would do it (per their docs):

```javascript
$.ajax({
  url: "https://opencity.fcgov.com/resource/ykei-s9zt.json",
  type: "GET",
  data: {
    "$limit" : 5000,
    "$$app_token" : "Grl9BP2WdpCsAdxGtNqLSkuNr"
  }
}).done(function(data) {
  // Do stuff with data...
});
```

**Comment by abettermap** [comment]
Here's a working demo in CodePen: https://codepen.io/anon/pen/ERVOOY
