### ISSUE TITLE
Get Socrata app token

### ISSUE THREAD

**Issue by abettermap** [CodeForFoco/solar-scorecard#37]
@ijskor 

We should probably get an app token because:

> You can make a certain number of requests without an application token, but they come from a shared pool and you’re eventually going to get cut off.
> 
> If you want more requests, register for an application token and your application will be granted up to 1000 requests per rolling hour period. If you need even more than that, special exceptions are made by request. 

Steps:

1. create a dev acct here: https://opendata.socrata.com/login (click `Sign Up`)
1. https://dev.socrata.com/register
1. get an app token https://opencity.fcgov.com/profile/app_tokens

**Comment by ijskor** [comment]
App Token
Grl9BP2WdpCsAdxGtNqLSkuNr

**Comment by ijskor** [comment]
@abettermap , I think we just have to sit down one day and get this done? I know we started it...

**Comment by abettermap** [comment]
@ijskor 

I think you already gave it to me in Slack, so I'll close this and we can move forward with #36 .
