### ISSUE TITLE
Update Graph

### ISSUE THREAD

**Issue by ijskor** [CodeForFoco/solar-scorecard#38]
It looks like the graph is showing by kW year right now, we also need to show cumulative so that we reach our goal.

What would be the best way to compare Fort Collins to Boulder? In the same graph or toggle between two graphs?

**Comment by ijskor** [comment]
Spelling Mistake: "Fort Collins Climate Goal: kW **Electricity**"

**Comment by abettermap** [comment]
I think a button or checkbox to toggle Boulder's data on the same graph would make sense.

**Comment by davidbhayes** [comment]
This is in the chart, I believe. Closing
