### ISSUE TITLE
Logo!

### ISSUE THREAD

**Issue by ijskor** [CodeForFoco/solar-scorecard#39]
We will need a kickass logo. I have some friends that may be interested in designing one and could always use fiverr. If anyone else has ideas, please submit!

**Comment by deidyomega** [comment]
My fiancee is an amazing artist.  Why don't we use this issue to describe it, and let your friends create a few designs, and let my fiancee create something, and we pick the best.

**Comment by ijskor** [comment]
Sounds Great! 
Here is some of my descriptives to get a logo in the right direction & of course welcome to more input and ideas:

Goal: Create a simple and attractive logo that clearly defines the goal of the group, excites the public, and influences cities to reach solar energy goals to become sustainable communities. 

- Should be a rebrandable logo - where cities want to use the logo to describe the state of their solar. Maybe could also be used by users in the future as badges for their input to the solar goal. 

- Common Themes: Solar Panels, Sun, Environment, Sustainability, Environment, Energy Independence, Race to be the most renewable

-Other Considerations: Might evolve into all renewables.

**Comment by abettermap** [comment]
[This one](http://recycle.com/wp-content/uploads/2014/05/SustSco.png) is kinda cool, although it doesn't involve any identifiable icons.

What about a mashup/combo of a [graph icon](https://www.google.com/search?q=graph+icon&num=20&tbm=isch&tbo=u&source=univ&sa=X&ved=0ahUKEwiYl-ihho_YAhUMzWMKHRhqAUwQsAQIKA&biw=1600&bih=799) and a [solar/sun thing](https://www.google.com/search?q=solar+icon&num=20&tbm=isch&tbo=u&source=univ&sa=X&ved=0ahUKEwigluO4ho_YAhVV02MKHbzrB5IQsAQIKA&biw=1600&bih=799)?

**Comment by ijskor** [comment]
Got the logo, Will upload. Where is the best spot to upload to Github?

**Comment by abettermap** [comment]
Closing this, #43 takes its place.
