### ISSUE TITLE
Make `npm start` work with new setup

### ISSUE THREAD

**Issue by abettermap** [CodeForFoco/solar-scorecard#41]
Material Design has different dir structure, need to modify `npm start` to work with new setup.

**Comment by ijskor** [comment]
Also Teach Ian how to work on website html.

**Comment by abettermap** [comment]
"new setup" will be different yet, since we are rolling with [Vue Material](https://vuematerial.io/) which will probably have some Webpack craziness.

**Comment by abettermap** [comment]
Didn't have to change much. 

Related but different: #54
