### ISSUE TITLE
Upload Logos

### ISSUE THREAD

**Issue by ijskor** [CodeForFoco/solar-scorecard#43]
- [x] Upload Scorecard Logo to Website
- [ ] Upload Code for FoCo logo to website (defined as developed by)
- [ ] Upload Sandbox Solar logo to website (defined as Hosted by)

**Comment by ijskor** [comment]
![solar scorecard logo final](https://user-images.githubusercontent.com/28639805/35297241-a2a422da-003b-11e8-9fe2-6bc0a826a5e3.png)
![sandboxsolarlogofinal](https://user-images.githubusercontent.com/28639805/35297258-af80b9be-003b-11e8-8827-97e0ba39edf7.png)

**Comment by abettermap** [comment]
@ijskor 

Can you get these in SVG format? It should result in a smaller file size and infinite scalability, so win-win.

**Comment by abettermap** [comment]
If you can't get SVG, we should at least optimize a bit before uploading as they are quite large as PNG.

I think putting them in a folder called *code/img/logos* would be perf. If you can't make folders directly on Github, let me know and I'll walk you through the Git steps.

**Comment by ijskor** [comment]
Created folder, working on getting SVG files

**Comment by ijskor** [comment]
Uploaded SVG file to img/logos folder

**Comment by abettermap** [comment]
@ijskor Looks good. Nice and crisp. Are you able to remove the white background behind "SOLAR"? Not noticeable if the logo is on top of a white background already, but it will be obvious in any other scenario:

![image](https://user-images.githubusercontent.com/4974087/36955103-900eaa38-1fe3-11e8-922d-2e1a5cfc3c68.png)

**Comment by ijskor** [comment]
Let's try this

**Comment by abettermap** [comment]
If you want to check it when you've committed, you can go to the commit in GitHub then click **View**. For example, [here it is at your new commit](https://github.com/CodeForFoco/solar-scorecard/blob/25313f18fc2f2f50c7523a72abfc67d222c5d7a4/img/solar%20scorecard%20logo%20v3%20text%20(1).svg).

**Comment by ijskor** [comment]
Yep, noticed that. I uploaded a new one my friend sent to me today, but didn't look like it was right again. So I'll get back to you.

**Comment by ijskor** [comment]
Wooo! It looks like the most recent version is working. Let me know if it works for you too @abettermap

**Comment by abettermap** [comment]
Perf!
