### ISSUE TITLE
Create Personalized Icons List

### ISSUE THREAD

**Issue by ijskor** [CodeForFoco/solar-scorecard#45]
Create Icon Pallet to Match Theme/Logo
- [ ] Main Page (Image of Graph)
- [ ] Get Involved
- [ ] Contact 
- [ ] About Us

**Comment by abettermap** [comment]
@ijskor 

[Material Icons](https://material.io/icons/) are included, so let me know which ones look good. If you want to change them yourself, lines like [this](https://github.com/CodeForFoco/solar-scorecard/blob/master/index.html#L36) and [this](https://github.com/CodeForFoco/solar-scorecard/blob/master/index.html#L41) are responsible for the icons.

**Comment by davidbhayes** [comment]
We're using Material icons now :)
