### ISSUE TITLE
Layout and Design 'Contact Page'

### ISSUE THREAD

**Issue by ijskor** [CodeForFoco/solar-scorecard#46]
**About Solar Scorecard:**
List Information from this Readme

**Team:**

1. Code for FoCo (Development)
"Code for Fort Collins is a volunteer organization who develops technology-driven solutions to challenges faced by charities, government agencies, and other groups within the city.

We are community members who want to have a positive impact on Fort Collins. By finding problems, refining solutions, and building them out, we grow professionally and learn new technical skills."

2. Sandbox Solar (Host)

**Partners**
City of Fort Collins
City of Boulder

Add Contact form in order to "Become a Partner"

**Comment by ijskor** [comment]
https://docs.google.com/presentation/d/1yvU1mrrRvSsusBKYDANre6Z_xYVQeyc6J5xIpUXXR3M/edit?usp=sharing
![website layout 3](https://user-images.githubusercontent.com/28639805/35541285-3d953f6a-0517-11e8-8342-554a0ef94a4c.jpg)

**Comment by davidbhayes** [comment]
Closing with 7c28e2ea755b3938ce55150ef7b8710d6f5b1c38
