### ISSUE TITLE
Layout and Design "Get Involved"

### ISSUE THREAD

**Issue by ijskor** [CodeForFoco/solar-scorecard#48]
Split Page into 3 Sections (Home, Business, Community)

![dji_0014](https://user-images.githubusercontent.com/28639805/35259302-50a51012-ffc2-11e7-9d4f-6212390f12d0.JPG)
"Description"
"Link to sandboxsolar.com"

![dji_0006 3](https://user-images.githubusercontent.com/28639805/35259286-37b8f83e-ffc2-11e7-96ec-1b353cc22f36.JPG)
"Description"
"Link to http://sandboxsolar.com/commercial-solar-installation"

![community solar image 1](https://user-images.githubusercontent.com/28639805/35259316-6807a27e-ffc2-11e7-8690-7ff9200f6378.jpg)
"Description"
"Link to http://sandboxsolar.com/community"

**Comment by ijskor** [comment]
https://docs.google.com/presentation/d/1yvU1mrrRvSsusBKYDANre6Z_xYVQeyc6J5xIpUXXR3M/edit?usp=sharing

![website layout 1](https://user-images.githubusercontent.com/28639805/35541253-1db4d372-0517-11e8-83ab-e12ded9d96df.jpg)

**Comment by davidbhayes** [comment]
Can we get the text that explains how to add solar at Home, Business, and Community?
