### ISSUE TITLE
Create Font Theme of Website

### ISSUE THREAD

**Issue by ijskor** [CodeForFoco/solar-scorecard#52]
The Logo has a font type of Charlevoix Pro - 
You can request to edit and extract from my link:
https://drive.google.com/drive/folders/1nNBwdvawJIj0aVWezK9d7VaabQDYsNBs?usp=sharing

Otherwise, another font type is fine too if we find a matching one.

**Comment by abettermap** [comment]
Vue Material [recommends Roboto](https://vuematerial.io/getting-started/):

> It's optional, but to have the best experience possible, use Roboto and Google Icons from Google CDN

...so we should roll with that.

**Comment by ijskor** [comment]
Yeah looks good :+1:
