### ISSUE TITLE
Get an error while `npm start` on Windows OS

### ISSUE THREAD

**Issue by happyzhanls** [CodeForFoco/solar-scorecard#58]
Not really an issue for me now, but just to reference a solution link for someone who may come across the same problem as me.

This is the problem, basically the system cannot find the packages that it needs to run.
<img width="960" alt="capture" src="https://user-images.githubusercontent.com/23114302/38402237-0623ab36-3918-11e8-9792-4d341a917423.PNG">

I solved this by just installing two missing packages like this:
`npm install --save-dev babel-preset-es2015 babel-preset-stage-2`

And the solution can also be found here -> [https://github.com/babel/gulp-babel/issues/93](https://github.com/babel/gulp-babel/issues/93)

**Comment by abettermap** [comment]
Thanks for pointing this out. Would you mind submitting a Pull Request with the fix? It should just be the package.json file that has changed.

**Comment by abettermap** [comment]
Closed by #59
