### ISSUE TITLE
Get some fake data

### ISSUE THREAD

**Issue by abettermap** [CodeForFoco/solar-scorecard#7]
Might not have real data for awhile, so let's make something realistic. Maybe using [Faker]( https://cdn.rawgit.com/Marak/faker.js/master/examples/browser/index.html).

**Comment by abettermap** [comment]
Actually, I don't think Faker would be that useful for us. We really just need a small handful of custom columns. Turns out d3 actually has a built-in thing we might be able to leverage: https://github.com/d3/d3/blob/master/API.md#random-numbers-d3-random

**Comment by deidyomega** [comment]
My last pull request (https://github.com/CodeForFoco/solar-scorecard/pull/15), I created a simple line_generator() function that does a pretty good job of creating randomish lines with a high R^2 (meaning it's a straightish line). 

If you guys can tell me the approx values of the real data, I can have my line_generator() create numbers within 1 - 2 stdevs of that approximation.

**Comment by abettermap** [comment]
Cool, let's hit Ian up on Slack to see if he can produce some values.

**Comment by ijskor** [comment]
[Solaredge Sample Data.xlsx](https://github.com/CodeForFoco/solar-scorecard/files/1104148/Solaredge.Sample.Data.xlsx)

**Comment by ijskor** [comment]
Try some of that, I can get more if needed. We will be collecting the 'kW' data primarily.

**Comment by deidyomega** [comment]
I posted in the slack, but the sample data has massive changes in kw / month.  Unless I'm reading this excel incorrectly.

If this spike it a trend that's expected to continue, I'll need to create a exponential regression.  Or do you think that now the new stations are online a linear model will be a more accurate projection?
